server:
  port: 8080

spring:
  application:
    name: Spring Security

  datasource:
    url: jdbc:postgresql://localhost:5432/Security
    password: 12345
    username: admin

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: on